### ISSUE TITLE
Suddenly stopped working.

### ISSUE THREAD

**Issue by rainwoodman** [nickhand/classylss#3] opened 2016-12-16 19:53 UTC
```
MPITest(commsize=1):test_fftpower ... FlatLambdaCDM(name="Planck15", H0=67.7 km / (Mpc s), Om0=0.307, Tcmb0=2.725 K, Neff=3.05, m_nu=[ 0.    0.    0.06] eV, Ob0=0.0486)


Error in thermodynamics_init 
=>thermodynamics_init(L:301) :error in thermodynamics_helium_from_bbn(ppr,pba,pth);
=>thermodynamics_helium_from_bbn(L:1112) :could not open fA with name /usr/lib64/python2.7/site-packages/classylss/class/bbn/sBBN.dat and mode "r"
ERROR
```

**Comment by rainwoodman** [comment] 2016-12-16 20:09
Installed from pypi 0.1.5, with --user. The problem goes away when I installed from the source code with pip install .

**Comment by nickhand** [comment] 2016-12-17 18:38
What's the output when you install with --user? I think this is related to a bug in wheel. What wheel and pip versions do you have? I can't reproduce this running with the latest versions.

The install directory gets passed to CLASS when building it, and there's a bug in wheel that prevents wheel from succeeded, but only after using the wrong install directory (I think)

**Comment by nickhand** [comment] 2016-12-17 19:54
I believe this should be fixed in 0.1.7 via a workaround in d2a0796

**Comment by rainwoodman** [comment] 2016-12-17 21:45
I am not really sure. Looks like it is because the cache was built against not '--user', then install failed -- then I installed with --user. The problem is the path is hard coded when class is built. A clean approach would be modifying class such that the path can be customized at run time, and the binding passes the path to class.

**Comment by rainwoodman** [comment] 2016-12-17 21:58
You can override the file names by setting BBN file key to any file. The default (when no key exists) is set herehttps://github.com/lesgourg/class_public/blob/f798efb41e324f158286358f3397a2b3b45f27a8/source/input.c#L3114
You can overrided according to 
https://github.com/lesgourg/class_public/blob/f798efb41e324f158286358f3397a2b3b45f27a8/source/input.c#L2435

**Comment by rainwoodman** [comment] 2016-12-17 21:59
Some other files are
https://github.com/lesgourg/class_public/blob/f798efb41e324f158286358f3397a2b3b45f27a8/source/input.c#L3152

**Comment by rainwoodman** [comment] 2016-12-17 22:00
Turns out `__CLASSDIR` is only used in those places, so we can in princple set CLASSDIR to some plain invalid name ('/' for example) and always override the path from the package dir. I'll take a look at this.

**Comment by rainwoodman** [comment] 2016-12-18 00:37
I emailed you a patch.

**Closed** 2016-12-18 23:22 UTC
